// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi6qirbUu2YayPKZSIQaQ0u2ysTCTnt1E',
    appId: '1:819418201781:web:2ef655924cbcd40fdfc8fc',
    messagingSenderId: '819418201781',
    projectId: 'my-food-app-cd514',
    authDomain: 'my-food-app-cd514.firebaseapp.com',
    storageBucket: 'my-food-app-cd514.firebasestorage.app',
    measurementId: 'G-H9KSSZBKQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Qpq-TZmtcCXdsf2y1_IAFqhbtCcvMf0',
    appId: '1:819418201781:android:4cfc27f9fec9c603dfc8fc',
    messagingSenderId: '819418201781',
    projectId: 'my-food-app-cd514',
    storageBucket: 'my-food-app-cd514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT4s2zMlWDdAGby3JG0MZYI5328K9L6sY',
    appId: '1:819418201781:ios:a9816d7cce02c47ddfc8fc',
    messagingSenderId: '819418201781',
    projectId: 'my-food-app-cd514',
    storageBucket: 'my-food-app-cd514.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT4s2zMlWDdAGby3JG0MZYI5328K9L6sY',
    appId: '1:819418201781:ios:a9816d7cce02c47ddfc8fc',
    messagingSenderId: '819418201781',
    projectId: 'my-food-app-cd514',
    storageBucket: 'my-food-app-cd514.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi6qirbUu2YayPKZSIQaQ0u2ysTCTnt1E',
    appId: '1:819418201781:web:5af6fabc158fe3b8dfc8fc',
    messagingSenderId: '819418201781',
    projectId: 'my-food-app-cd514',
    authDomain: 'my-food-app-cd514.firebaseapp.com',
    storageBucket: 'my-food-app-cd514.firebasestorage.app',
    measurementId: 'G-3EW3E1Y7K4',
  );

}